<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <!-- Spring Boot parent -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
        <relativePath/>
    </parent>

    <groupId>com.ecom</groupId>

    <artifactId>22-Project3-Order-Processing-System-Microservices-Kafka</artifactId>

    <version>0.0.1-SNAPSHOT</version>

    <packaging>pom</packaging>

    <name>22-Project3-Order-Processing-System-Microservices-Kafka</name>

    <description>
        An event-driven Order Processing System using Spring Boot Microservices and Apache Kafka
    </description>

    <!-- Child modules -->
    <modules>
        <module>order-service</module>
        <module>payment-service</module>
        <module>delivery-service</module>
        <module>notification-service</module>
        
    </modules>

</project>